name: build cache artifact #######

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: recuperation projet
      uses: actions/checkout@v4

    - name: JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: dependances cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: build
      run: mvn install

    - name: upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./target/*.jar