name: build cache artifact #######

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: recuperation projet
      uses: actions/checkout@v4

    - name: JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: dependances cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: build
      run: mvn install -DskipTests
      
    - name: test
      run: mvn test
      continue-on-error: true
      
    - name: build docker image
      run: |
        docker build -t huproz/cicd_git_actions:latest .
        
    - name: login dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push dockerhub
      run: |
        docker push huproz/cicd_git_actions:latest

    - name: upload build artifact
      if: github.ref == 'refs/heads/main' && success()
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./target/*.jar