name: Auto-respond to new issues

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Respond to issue
      uses: actions/github-script@v6
      with:
        script: |
          const issueComment = `
          Merci d'avoir ouvert cette issue ! Nous allons examiner votre demande et revenir vers vous dès que possible.

          Si vous avez des informations supplémentaires à fournir, n'hésitez pas à les ajouter ici.
          `;

          if (github && github.issues && github.issues.createComment) {
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });
          } else {
            console.error('github.issues.createComment is not available');
          }
