name: auto-rep issue

on:
  issues:
    types: [opened]

jobs:
  rep:
    runs-on: ubuntu-latest
    steps:
      - name: repondre
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Bonjour, merci d'avoir ouvert une issue ! Nous allons l'examiner dès que possible.