name: auto-rep issue

on:
  issues:
    types: [opened]

jobs:
  rep:
    runs-on: ubuntu-latest
    steps:
      - name: repondre
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Bonjour ${{ github.event.issue.user.login }}, nous avons bien pris en compte votre problème du nom de : ${{ github.event.issue.title }}