name: test

on:
  push:

jobs:
  jobtest:
    runs-on: ubuntu-latest

    steps:
      - name: recup projet
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: dependances
        run: mvn install

      - name: build
        run: mvn package
